// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/list-recent-trades.ts
import { createClient } from "npm:@supabase/supabase-js@^2.100.1";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.25.76";
function supabaseForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_recent_trades_default = defineTool({
  name: "list_recent_trades",
  title: "List recent trades",
  description: "List the signed-in user's most recent trades from TG Master Journal, ordered by date. Returns core fields (asset, direction, session, setup, grade, planned/actual RR, P/L, result).",
  inputSchema: {
    limit: z.number().int().min(1).max(100).default(20).describe("Max trades to return (1-100). Default 20.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "Not authenticated." }], isError: true };
    const sb = supabaseForUser(ctx);
    const { data, error } = await sb.from("trades").select(
      "id,date,asset,market,direction,session,setup,grade,planned_rr,actual_rr,profit_loss,result,status"
    ).eq("user_id", ctx.getUserId()).order("date", { ascending: false }).limit(limit ?? 20);
    if (error)
      return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { trades: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-trades.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^3.25.76";

// src/lib/mcp/lib/client.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.100.1";
function supabaseForUser2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
function unauthenticated() {
  return {
    content: [{ type: "text", text: "Not authenticated. Sign in to TG Master Journal first." }],
    isError: true
  };
}
function failure(message) {
  return { content: [{ type: "text", text: message }], isError: true };
}
function ok(payload) {
  return {
    content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
    structuredContent: payload
  };
}
var isWin = (r) => String(r ?? "").toLowerCase() === "win";
var isLoss = (r) => String(r ?? "").toLowerCase() === "loss";
var isBreakeven = (r) => String(r ?? "").toLowerCase() === "breakeven";
var isExecuted = (row) => (isWin(row.result) || isLoss(row.result) || isBreakeven(row.result)) && String(row.status ?? "Complete").toLowerCase() !== "draft";
var num = (v) => Number.isFinite(Number(v)) ? Number(v) : 0;
var round = (v, d = 2) => +v.toFixed(d);

// src/lib/mcp/tools/list-trades.ts
var TRADE_LIST_FIELDS = "id,date,entry_time,exit_time,market,asset,direction,session,setup,grade,result,status,planned_rr,actual_rr,pips,profit_loss,market_condition,timeframe";
var list_trades_default = defineTool2({
  name: "list_trades",
  title: "List and filter trades",
  description: "List the signed-in user's trades with optional filters (pair/asset, session, setup, grade, result, direction, market, date range) plus sorting and pagination. Returns core trade fields.",
  inputSchema: {
    asset: z2.string().optional().describe("Filter by pair/asset symbol, e.g. XAUUSD."),
    session: z2.string().optional().describe("Filter by session, e.g. London, New York."),
    setup: z2.string().optional().describe("Filter by setup name."),
    grade: z2.string().optional().describe("Filter by trade grade: A+, A, B, C."),
    result: z2.string().optional().describe("Filter by result: Win, Loss, Breakeven, Untriggered Setup, Cancelled."),
    direction: z2.string().optional().describe("Filter by direction: Long or Short."),
    market: z2.string().optional().describe("Filter by market, e.g. Forex, Crypto, Indices."),
    from: z2.string().optional().describe("Start date (inclusive) in YYYY-MM-DD."),
    to: z2.string().optional().describe("End date (inclusive) in YYYY-MM-DD."),
    min_rr: z2.number().optional().describe("Only trades whose actual RR is >= this value."),
    sort: z2.string().optional().describe("Sort field: date, profit_loss, actual_rr, planned_rr. Default date."),
    order: z2.string().optional().describe("Sort order: asc or desc. Default desc."),
    limit: z2.number().int().min(1).max(200).default(50).describe("Page size (1-200). Default 50."),
    offset: z2.number().int().min(0).default(0).describe("Rows to skip for pagination. Default 0.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    const {
      asset: asset2,
      session,
      setup,
      grade,
      result,
      direction,
      market,
      from,
      to,
      min_rr,
      sort,
      order,
      limit,
      offset
    } = input;
    const sortField = ["date", "profit_loss", "actual_rr", "planned_rr"].includes(String(sort)) ? String(sort) : "date";
    const ascending = String(order ?? "desc").toLowerCase() === "asc";
    const take = limit ?? 50;
    const skip = offset ?? 0;
    const sb = supabaseForUser2(ctx);
    let q = sb.from("trades").select(TRADE_LIST_FIELDS, { count: "exact" }).eq("user_id", ctx.getUserId());
    if (asset2) q = q.ilike("asset", asset2);
    if (session) q = q.ilike("session", session);
    if (setup) q = q.ilike("setup", setup);
    if (grade) q = q.eq("grade", grade);
    if (result) q = q.ilike("result", result);
    if (direction) q = q.ilike("direction", direction);
    if (market) q = q.ilike("market", market);
    if (from) q = q.gte("date", from);
    if (to) q = q.lte("date", to);
    if (typeof min_rr === "number") q = q.gte("actual_rr", min_rr);
    const { data, error, count } = await q.order(sortField, { ascending }).range(skip, skip + take - 1);
    if (error) return failure(error.message);
    return ok({
      trades: data ?? [],
      pagination: {
        limit: take,
        offset: skip,
        returned: (data ?? []).length,
        total: count ?? null,
        has_more: count != null ? skip + (data ?? []).length < count : null
      }
    });
  }
});

// src/lib/mcp/tools/get-trade.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^3.25.76";

// src/lib/mcp/lib/media.ts
var PREFIX = "urlmeta:";
function b64decode(value) {
  try {
    const bytes = Uint8Array.from(
      // eslint-disable-next-line no-restricted-globals
      globalThis.atob ? globalThis.atob(value) : Buffer.from(value, "base64").toString("binary"),
      (c) => c.charCodeAt(0)
    );
    return new TextDecoder().decode(bytes);
  } catch {
    return "";
  }
}
function rawUrl(value) {
  const s = typeof value === "string" ? value : "";
  if (!s.startsWith(PREFIX)) return s;
  const json = b64decode(s.slice(PREFIX.length));
  try {
    const parsed = JSON.parse(json);
    if (parsed && typeof parsed.url === "string") return parsed.url;
  } catch {
  }
  return s;
}
var BUCKET = "journal-media";
function storagePath(value) {
  const url = rawUrl(value);
  if (!url) return null;
  const m = url.match(/\/storage\/v1\/object\/(?:sign|public|authenticated)\/journal-media\/([^?#]+)/);
  if (m) {
    try {
      return decodeURIComponent(m[1]);
    } catch {
      return m[1];
    }
  }
  if (/^https?:|^data:|^blob:/i.test(url)) return null;
  return url.replace(/^\/*/, "").replace(/^journal-media\//, "") || null;
}
function collectPaths(value, out = /* @__PURE__ */ new Set(), depth = 0) {
  if (value == null || depth > 8) return out;
  if (typeof value === "string") {
    const p = storagePath(value);
    if (p) out.add(p);
    return out;
  }
  if (Array.isArray(value)) {
    for (const v of value) collectPaths(v, out, depth + 1);
    return out;
  }
  if (typeof value === "object") {
    for (const v of Object.values(value)) collectPaths(v, out, depth + 1);
  }
  return out;
}

// src/lib/mcp/tools/get-trade.ts
var get_trade_default = defineTool3({
  name: "get_trade",
  title: "Get a trade by ID",
  description: "Fetch one full trade record (including notes, confluences, psychology, management and analysis) by its ID, scoped to the signed-in user. Any chart screenshots are returned as freshly signed, currently valid URLs in `media` (and the image fields are refreshed in place), because the URLs stored on the row expire.",
  inputSchema: {
    id: z3.string().describe("The trade ID."),
    expires_in: z3.number().int().min(60).max(86400).default(3600).describe("Lifetime in seconds for the freshly signed media URLs (60-86400). Default 3600.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ id, expires_in }, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    const sb = supabaseForUser2(ctx);
    const { data, error } = await sb.from("trades").select("*").eq("user_id", ctx.getUserId()).eq("id", id).maybeSingle();
    if (error) return failure(error.message);
    if (!data) return failure(`No trade found with id "${id}".`);
    const trade = data;
    const ttl = expires_in ?? 3600;
    const paths = Array.from(collectPaths(trade));
    let signed = /* @__PURE__ */ new Map();
    if (paths.length) {
      const { data: urls } = await sb.storage.from(BUCKET).createSignedUrls(paths, ttl);
      signed = new Map(
        (urls ?? []).filter((u) => u?.signedUrl).map((u) => [String(u.path), u.signedUrl])
      );
    }
    for (const field of ["prediction_image", "execution_image"]) {
      const p = storagePath(trade[field]);
      const fresh = p ? signed.get(p) : null;
      if (fresh) trade[field] = fresh;
    }
    return ok({
      trade,
      media: paths.map((p) => ({ path: p, signed_url: signed.get(p) ?? null })),
      media_expires_in: ttl
    });
  }
});

// src/lib/mcp/tools/search-trades.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z4 } from "npm:zod@^3.25.76";
var search_trades_default = defineTool4({
  name: "search_trades",
  title: "Search trades by text",
  description: "Free-text search across the signed-in user's trades. Matches notes, setup, asset, session and grade. Use for questions like 'losing XAUUSD trades' or 'trades where I mention FOMO'.",
  inputSchema: {
    query: z4.string().describe("Text to search for in notes, setup, asset or session."),
    limit: z4.number().int().min(1).max(100).default(25).describe("Max rows to return. Default 25."),
    offset: z4.number().int().min(0).default(0).describe("Rows to skip for pagination.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, limit, offset }, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    const take = limit ?? 25;
    const skip = offset ?? 0;
    const term = String(query).replace(/[,()]/g, " ").trim();
    if (!term) return failure("Query must not be empty.");
    const pattern = `%${term}%`;
    const sb = supabaseForUser2(ctx);
    const { data, error, count } = await sb.from("trades").select(`${TRADE_LIST_FIELDS},notes`, { count: "exact" }).eq("user_id", ctx.getUserId()).or(
      [
        `notes.ilike.${pattern}`,
        `setup.ilike.${pattern}`,
        `asset.ilike.${pattern}`,
        `session.ilike.${pattern}`,
        `grade.ilike.${pattern}`
      ].join(",")
    ).order("date", { ascending: false }).range(skip, skip + take - 1);
    if (error) return failure(error.message);
    return ok({
      query: term,
      matches: data ?? [],
      pagination: { limit: take, offset: skip, returned: (data ?? []).length, total: count ?? null }
    });
  }
});

// src/lib/mcp/tools/get-trade-stats.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.100.1";
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z5 } from "npm:zod@^3.25.76";
function supabaseForUser3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_trade_stats_default = defineTool5({
  name: "get_trade_stats",
  title: "Get trade performance stats",
  description: "Compute aggregate performance stats (trade count, win rate, total P/L, average R) across the signed-in user's trades, optionally filtered to the last N days.",
  inputSchema: {
    days: z5.number().int().min(1).max(3650).optional().describe("Only include trades from the last N days. Omit for all-time stats.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ days }, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "Not authenticated." }], isError: true };
    const sb = supabaseForUser3(ctx);
    let q = sb.from("trades").select("profit_loss,actual_rr,result,date").eq("user_id", ctx.getUserId());
    if (days) {
      const since = new Date(Date.now() - days * 864e5).toISOString().slice(0, 10);
      q = q.gte("date", since);
    }
    const { data, error } = await q;
    if (error)
      return { content: [{ type: "text", text: error.message }], isError: true };
    const rows = data ?? [];
    const count = rows.length;
    const wins = rows.filter((r) => r.result === "win").length;
    const losses = rows.filter((r) => r.result === "loss").length;
    const pnl = rows.reduce((s, r) => s + (Number(r.profit_loss) || 0), 0);
    const rValues = rows.map((r) => Number(r.actual_rr)).filter((v) => Number.isFinite(v));
    const avgR = rValues.length ? rValues.reduce((a, b) => a + b, 0) / rValues.length : 0;
    const stats = {
      window: days ? `last ${days} days` : "all time",
      trades: count,
      wins,
      losses,
      win_rate_pct: count ? +(wins / count * 100).toFixed(2) : 0,
      total_profit_loss: +pnl.toFixed(2),
      average_r: +avgR.toFixed(3)
    };
    return {
      content: [{ type: "text", text: JSON.stringify(stats, null, 2) }],
      structuredContent: stats
    };
  }
});

// src/lib/mcp/tools/get-performance-metrics.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z6 } from "npm:zod@^3.25.76";

// src/lib/mcp/lib/analytics.ts
function computeMetrics(rows) {
  const executed = rows.filter(isExecuted);
  const wins = executed.filter((r) => isWin(r.result));
  const losses = executed.filter((r) => isLoss(r.result));
  const breakevens = executed.filter((r) => isBreakeven(r.result));
  const grossProfit = wins.reduce((s, r) => s + Math.max(num(r.profit_loss), 0), 0);
  const grossLoss = Math.abs(losses.reduce((s, r) => s + Math.min(num(r.profit_loss), 0), 0));
  const netPnl = executed.reduce((s, r) => s + num(r.profit_loss), 0);
  const winRate = executed.length ? wins.length / executed.length * 100 : 0;
  const avgWin = wins.length ? grossProfit / wins.length : 0;
  const avgLoss = losses.length ? grossLoss / losses.length : 0;
  const rValues = executed.map((r) => Number(r.actual_rr)).filter((v) => Number.isFinite(v));
  const avgR = rValues.length ? rValues.reduce((a, b) => a + b, 0) / rValues.length : 0;
  const plannedR = executed.map((r) => Number(r.planned_rr)).filter((v) => Number.isFinite(v));
  return {
    total_trades: rows.length,
    executed_trades: executed.length,
    wins: wins.length,
    losses: losses.length,
    breakevens: breakevens.length,
    win_rate_pct: round(winRate),
    net_profit_loss: round(netPnl),
    gross_profit: round(grossProfit),
    gross_loss: round(grossLoss),
    profit_factor: grossLoss > 0 ? round(grossProfit / grossLoss, 3) : grossProfit > 0 ? null : 0,
    expectancy_per_trade: executed.length ? round(netPnl / executed.length) : 0,
    expectancy_r: round(winRate / 100 * (avgLoss ? avgWin / avgLoss : 0) - (1 - winRate / 100), 3),
    average_win: round(avgWin),
    average_loss: round(avgLoss),
    average_actual_r: round(avgR, 3),
    average_planned_r: plannedR.length ? round(plannedR.reduce((a, b) => a + b, 0) / plannedR.length, 3) : 0,
    best_trade: executed.length ? round(Math.max(...executed.map((r) => num(r.profit_loss)))) : 0,
    worst_trade: executed.length ? round(Math.min(...executed.map((r) => num(r.profit_loss)))) : 0
  };
}
function groupPerformance(rows, key) {
  const buckets = /* @__PURE__ */ new Map();
  for (const row of rows.filter(isExecuted)) {
    const k = String(row[key] ?? "Unspecified");
    buckets.set(k, [...buckets.get(k) ?? [], row]);
  }
  return [...buckets.entries()].map(([label, group]) => {
    const m = computeMetrics(group);
    return {
      label,
      trades: m.executed_trades,
      win_rate_pct: m.win_rate_pct,
      net_profit_loss: m.net_profit_loss,
      profit_factor: m.profit_factor,
      average_actual_r: m.average_actual_r
    };
  }).sort((a, b) => b.net_profit_loss - a.net_profit_loss);
}
function monthKey(date2) {
  return (date2 ?? "").slice(0, 7);
}
function weekStart(date2) {
  if (!date2) return "";
  const d = /* @__PURE__ */ new Date(`${date2}T00:00:00Z`);
  if (Number.isNaN(d.getTime())) return "";
  const day = (d.getUTCDay() + 6) % 7;
  d.setUTCDate(d.getUTCDate() - day);
  return d.toISOString().slice(0, 10);
}
function equityCurve(rows, startingBalance = 0) {
  let running = startingBalance;
  let peak = startingBalance;
  let maxDrawdown = 0;
  const points = rows.filter(isExecuted).slice().sort((a, b) => String(a.date).localeCompare(String(b.date))).map((r) => {
    running += num(r.profit_loss);
    peak = Math.max(peak, running);
    maxDrawdown = Math.max(maxDrawdown, peak - running);
    return { date: r.date, pnl: round(num(r.profit_loss)), equity: round(running) };
  });
  return { points, ending_equity: round(running), peak_equity: round(peak), max_drawdown: round(maxDrawdown) };
}

// src/lib/mcp/tools/get-performance-metrics.ts
var get_performance_metrics_default = defineTool6({
  name: "get_performance_metrics",
  title: "Get performance metrics",
  description: "Compute the signed-in user's performance metrics: win rate, net P/L, profit factor, expectancy, average win/loss and average R. Optionally scoped to a date range, and optionally broken down by session, asset, setup or grade.",
  inputSchema: {
    from: z6.string().optional().describe("Start date (inclusive) in YYYY-MM-DD."),
    to: z6.string().optional().describe("End date (inclusive) in YYYY-MM-DD."),
    days: z6.number().int().min(1).max(3650).optional().describe("Alternative to from/to: last N days."),
    group_by: z6.string().optional().describe("Optional breakdown dimension: session, asset, setup or grade.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ from, to, days, group_by }, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    const sb = supabaseForUser2(ctx);
    let q = sb.from("trades").select("date,asset,session,setup,grade,result,status,profit_loss,actual_rr,planned_rr").eq("user_id", ctx.getUserId());
    const start = from ?? (days ? new Date(Date.now() - days * 864e5).toISOString().slice(0, 10) : void 0);
    if (start) q = q.gte("date", start);
    if (to) q = q.lte("date", to);
    const { data, error } = await q;
    if (error) return failure(error.message);
    const rows = data ?? [];
    const dim = ["session", "asset", "setup", "grade"].includes(String(group_by)) ? String(group_by) : null;
    return ok({
      window: { from: start ?? null, to: to ?? null },
      metrics: computeMetrics(rows),
      breakdown: dim ? { dimension: dim, groups: groupPerformance(rows, dim) } : null
    });
  }
});

// src/lib/mcp/tools/get-dashboard-summary.ts
import { defineTool as defineTool7 } from "npm:@lovable.dev/mcp-js@0.20.0";
var get_dashboard_summary_default = defineTool7({
  name: "get_dashboard_summary",
  title: "Get dashboard summary",
  description: "High-level snapshot of the signed-in user's journal: all-time and last-30-day performance, top sessions and pairs, account balances, and the most recent trades.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    const sb = supabaseForUser2(ctx);
    const uid = ctx.getUserId();
    const [tradesRes, accountsRes, recentRes] = await Promise.all([
      sb.from("trades").select("date,asset,session,setup,grade,result,status,profit_loss,actual_rr,planned_rr").eq("user_id", uid),
      sb.from("trading_accounts").select("id,name,broker,type,currency,starting_balance,current_size,status,stage").eq("user_id", uid),
      sb.from("trades").select("id,date,asset,direction,session,setup,grade,result,profit_loss,actual_rr").eq("user_id", uid).order("date", { ascending: false }).limit(10)
    ]);
    if (tradesRes.error) return failure(tradesRes.error.message);
    const rows = tradesRes.data ?? [];
    const since = new Date(Date.now() - 30 * 864e5).toISOString().slice(0, 10);
    const last30 = rows.filter((r) => String(r.date ?? "") >= since);
    return ok({
      all_time: computeMetrics(rows),
      last_30_days: computeMetrics(last30),
      top_sessions: groupPerformance(rows, "session").slice(0, 5),
      top_pairs: groupPerformance(rows, "asset").slice(0, 5),
      accounts: accountsRes.error ? [] : accountsRes.data ?? [],
      recent_trades: recentRes.error ? [] : recentRes.data ?? []
    });
  }
});

// src/lib/mcp/tools/get-equity-curve.ts
import { defineTool as defineTool8 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z7 } from "npm:zod@^3.25.76";
var get_equity_curve_default = defineTool8({
  name: "get_equity_curve",
  title: "Get equity curve",
  description: "Return the signed-in user's cumulative P/L curve over time, with peak equity and max drawdown. Optionally scoped to a date range and offset by a starting balance.",
  inputSchema: {
    from: z7.string().optional().describe("Start date (inclusive) in YYYY-MM-DD."),
    to: z7.string().optional().describe("End date (inclusive) in YYYY-MM-DD."),
    starting_balance: z7.number().optional().describe("Balance the curve starts from. Default 0.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ from, to, starting_balance }, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    const sb = supabaseForUser2(ctx);
    let q = sb.from("trades").select("date,result,status,profit_loss").eq("user_id", ctx.getUserId());
    if (from) q = q.gte("date", from);
    if (to) q = q.lte("date", to);
    const { data, error } = await q;
    if (error) return failure(error.message);
    return ok(equityCurve(data ?? [], starting_balance ?? 0));
  }
});

// src/lib/mcp/tools/get-period-stats.ts
import { defineTool as defineTool9 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z8 } from "npm:zod@^3.25.76";
var get_period_stats_default = defineTool9({
  name: "get_period_stats",
  title: "Get monthly or weekly statistics",
  description: "Break the signed-in user's performance down by month or by week (net P/L, win rate, profit factor, trade count per period). Useful for month-over-month comparison and weekly reporting.",
  inputSchema: {
    period: z8.string().optional().describe("Bucket size: 'month' (default) or 'week'."),
    from: z8.string().optional().describe("Start date (inclusive) in YYYY-MM-DD."),
    to: z8.string().optional().describe("End date (inclusive) in YYYY-MM-DD."),
    limit: z8.number().int().min(1).max(60).default(12).describe("Max periods returned, most recent first. Default 12.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ period, from, to, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    const sb = supabaseForUser2(ctx);
    let q = sb.from("trades").select("date,result,status,profit_loss,actual_rr,planned_rr").eq("user_id", ctx.getUserId());
    if (from) q = q.gte("date", from);
    if (to) q = q.lte("date", to);
    const { data, error } = await q;
    if (error) return failure(error.message);
    const bucketBy = String(period ?? "month").toLowerCase() === "week" ? weekStart : monthKey;
    const buckets = /* @__PURE__ */ new Map();
    for (const row of data ?? []) {
      const key = bucketBy(row.date);
      if (!key) continue;
      buckets.set(key, [...buckets.get(key) ?? [], row]);
    }
    const periods = [...buckets.entries()].sort((a, b) => b[0].localeCompare(a[0])).slice(0, limit ?? 12).map(([key, rows]) => ({ period: key, ...computeMetrics(rows) }));
    return ok({ granularity: String(period ?? "month").toLowerCase() === "week" ? "week" : "month", periods });
  }
});

// src/lib/mcp/tools/get-daily-plan.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.100.1";
import { defineTool as defineTool10 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z9 } from "npm:zod@^3.25.76";
function supabaseForUser4(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_daily_plan_default = defineTool10({
  name: "get_daily_plan",
  title: "Get daily trading plan",
  description: "Fetch the signed-in user's daily trading plan for a specific date (YYYY-MM-DD). Defaults to today when no date is supplied.",
  inputSchema: {
    date: z9.string().regex(/^\d{4}-\d{2}-\d{2}$/).optional().describe("Plan date in YYYY-MM-DD. Defaults to today.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ date: date2 }, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "Not authenticated." }], isError: true };
    const target = date2 ?? (/* @__PURE__ */ new Date()).toISOString().slice(0, 10);
    const sb = supabaseForUser4(ctx);
    const { data, error } = await sb.from("daily_plans").select("*").eq("user_id", ctx.getUserId()).eq("date", target).maybeSingle();
    if (error)
      return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data)
      return {
        content: [{ type: "text", text: `No daily plan found for ${target}.` }],
        structuredContent: { date: target, plan: null }
      };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { date: target, plan: data }
    };
  }
});

// src/lib/mcp/tools/list-daily-plans.ts
import { defineTool as defineTool11 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z10 } from "npm:zod@^3.25.76";
var list_daily_plans_default = defineTool11({
  name: "list_daily_plans",
  title: "List daily plans",
  description: "List the signed-in user's daily plans with bias, session focus, risk limits, review status and pair count. Use `get_daily_plan` for the full detail of one day.",
  inputSchema: {
    from: z10.string().optional().describe("Start date (inclusive) in YYYY-MM-DD."),
    to: z10.string().optional().describe("End date (inclusive) in YYYY-MM-DD."),
    reviewed: z10.boolean().optional().describe("Filter by whether the plan has been reviewed."),
    limit: z10.number().int().min(1).max(100).default(20).describe("Page size. Default 20."),
    offset: z10.number().int().min(0).default(0).describe("Rows to skip for pagination.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ from, to, reviewed, limit, offset }, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    const take = limit ?? 20;
    const skip = offset ?? 0;
    const sb = supabaseForUser2(ctx);
    let q = sb.from("daily_plans").select("id,date,daily_bias,session_focus,max_trades,risk_limit,pair_count,took_trades,reviewed,updated_at", {
      count: "exact"
    }).eq("user_id", ctx.getUserId());
    if (from) q = q.gte("date", from);
    if (to) q = q.lte("date", to);
    if (typeof reviewed === "boolean") q = q.eq("reviewed", reviewed);
    const { data, error, count } = await q.order("date", { ascending: false }).range(skip, skip + take - 1);
    if (error) return failure(error.message);
    return ok({
      plans: data ?? [],
      pagination: { limit: take, offset: skip, returned: (data ?? []).length, total: count ?? null }
    });
  }
});

// src/lib/mcp/tools/get-weekly-plan.ts
import { defineTool as defineTool12 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z11 } from "npm:zod@^3.25.76";
var get_weekly_plan_default = defineTool12({
  name: "get_weekly_plan",
  title: "Get weekly plan and review",
  description: "Fetch the signed-in user's weekly plan (bias, markets, setups, key levels, risk, goals, per-pair analyses, news and review notes) for a given week start date. Defaults to the most recent week.",
  inputSchema: {
    week_start: z11.string().optional().describe("Week start date in YYYY-MM-DD. Omit for the latest week.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ week_start }, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    const sb = supabaseForUser2(ctx);
    let q = sb.from("weekly_plans").select("*").eq("user_id", ctx.getUserId());
    if (week_start) q = q.eq("week_start", week_start);
    const { data, error } = await q.order("week_start", { ascending: false }).limit(1);
    if (error) return failure(error.message);
    const plan = (data ?? [])[0] ?? null;
    if (!plan)
      return ok({ week_start: week_start ?? null, plan: null, note: "No weekly plan found." });
    return ok({ week_start: plan.week_start, plan });
  }
});

// src/lib/mcp/tools/get-checklist.ts
import { defineTool as defineTool13 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z12 } from "npm:zod@^3.25.76";
function progress(sections) {
  const list = Array.isArray(sections) ? sections : [];
  const total = list.reduce((a, s) => a + (s.items?.length ?? 0), 0);
  const done = list.reduce((a, s) => a + (s.items ?? []).filter((i) => i.done).length, 0);
  return {
    total_items: total,
    completed_items: done,
    completion_pct: total ? round(done / total * 100) : 0,
    sections_completed: list.filter((s) => (s.items?.length ?? 0) > 0 && (s.items ?? []).every((i) => i.done)).length,
    sections_total: list.length
  };
}
function streak(rows) {
  const perfect = new Set(rows.filter((r) => progress(r.sections).completion_pct === 100).map((r) => r.date));
  let current = 0;
  const cursor = /* @__PURE__ */ new Date();
  for (; ; ) {
    const key = cursor.toISOString().slice(0, 10);
    if (perfect.has(key)) {
      current += 1;
      cursor.setUTCDate(cursor.getUTCDate() - 1);
      continue;
    }
    if (current === 0 && key === (/* @__PURE__ */ new Date()).toISOString().slice(0, 10)) {
      cursor.setUTCDate(cursor.getUTCDate() - 1);
      continue;
    }
    break;
  }
  let best = 0;
  let run = 0;
  let prev = null;
  for (const day of [...perfect].sort()) {
    if (prev) {
      const gap = (Date.parse(`${day}T00:00:00Z`) - Date.parse(`${prev}T00:00:00Z`)) / 864e5;
      run = gap === 1 ? run + 1 : 1;
    } else run = 1;
    best = Math.max(best, run);
    prev = day;
  }
  return { current_streak_days: current, longest_streak_days: best, perfect_days: perfect.size };
}
var get_checklist_default = defineTool13({
  name: "get_checklist",
  title: "Get trading checklist, progress and streak",
  description: "Fetch the signed-in user's daily trading checklist for a date (defaults to today) with per-section progress, plus recent history and completion streaks.",
  inputSchema: {
    date: z12.string().optional().describe("Checklist date in YYYY-MM-DD. Defaults to today."),
    history_days: z12.number().int().min(0).max(365).default(30).describe("How many days of history to include. Default 30, 0 to skip.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ date: date2, history_days }, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    const sb = supabaseForUser2(ctx);
    const uid = ctx.getUserId();
    const target = date2 ?? (/* @__PURE__ */ new Date()).toISOString().slice(0, 10);
    const days = history_days ?? 30;
    const { data: today, error } = await sb.from("trading_checklists").select("date,sections,updated_at").eq("user_id", uid).eq("date", target).maybeSingle();
    if (error) return failure(error.message);
    let history = [];
    if (days > 0) {
      const since = new Date(Date.now() - days * 864e5).toISOString().slice(0, 10);
      const res = await sb.from("trading_checklists").select("date,sections").eq("user_id", uid).gte("date", since).order("date", { ascending: false });
      if (res.error) return failure(res.error.message);
      history = res.data ?? [];
    }
    return ok({
      date: target,
      checklist: today ?? null,
      progress: today ? progress(today.sections ?? []) : null,
      history: history.map((h) => ({ date: h.date, ...progress(h.sections ?? []) })),
      streaks: streak(history)
    });
  }
});

// src/lib/mcp/tools/search-notebook.ts
import { defineTool as defineTool14 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z13 } from "npm:zod@^3.25.76";
var search_notebook_default = defineTool14({
  name: "search_notebook",
  title: "Search and list notebook entries",
  description: "List or free-text search the signed-in user's notebook/journal entries (pair, category, bias, journal text). Use for questions like 'notes about liquidity' or 'entries mentioning FOMO'.",
  inputSchema: {
    query: z13.string().optional().describe("Text to match in journal text, pair, category or bias. Omit to list all."),
    pair: z13.string().optional().describe("Filter by pair, e.g. XAUUSD."),
    category: z13.string().optional().describe("Filter by notebook category."),
    from: z13.string().optional().describe("Start date (inclusive) in YYYY-MM-DD."),
    to: z13.string().optional().describe("End date (inclusive) in YYYY-MM-DD."),
    limit: z13.number().int().min(1).max(100).default(25).describe("Page size. Default 25."),
    offset: z13.number().int().min(0).default(0).describe("Rows to skip for pagination.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, pair, category, from, to, limit, offset }, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    const take = limit ?? 25;
    const skip = offset ?? 0;
    const sb = supabaseForUser2(ctx);
    let q = sb.from("notebook_entries").select("id,entry_id,date,pair,category,bias,journal,legacy_notes,legacy_key_levels,updated_at", { count: "exact" }).eq("user_id", ctx.getUserId());
    if (pair) q = q.ilike("pair", pair);
    if (category) q = q.ilike("category", category);
    if (from) q = q.gte("date", from);
    if (to) q = q.lte("date", to);
    if (query) {
      const term2 = String(query).replace(/[,()]/g, " ").trim();
      if (term2) {
        const p = `%${term2}%`;
        q = q.or([`pair.ilike.${p}`, `category.ilike.${p}`, `bias.ilike.${p}`, `legacy_notes.ilike.${p}`].join(","));
      }
    }
    const { data, error, count } = await q.order("date", { ascending: false }).range(skip, skip + take - 1);
    if (error) return failure(error.message);
    const term = (query ?? "").trim().toLowerCase();
    const rows = term ? (data ?? []).filter((r) => JSON.stringify(r.journal ?? {}).toLowerCase().includes(term) || String(r.legacy_notes ?? "").toLowerCase().includes(term) || String(r.pair ?? "").toLowerCase().includes(term) || String(r.category ?? "").toLowerCase().includes(term)) : data ?? [];
    return ok({
      query: query ?? null,
      entries: rows,
      pagination: { limit: take, offset: skip, returned: rows.length, total: count ?? null }
    });
  }
});

// src/lib/mcp/tools/search-journal.ts
import { defineTool as defineTool15 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z14 } from "npm:zod@^3.25.76";

// src/lib/mcp/lib/text.ts
function flattenText(value, depth = 0) {
  if (value == null || depth > 8) return "";
  if (typeof value === "string") return value;
  if (typeof value === "number" || typeof value === "boolean") return String(value);
  if (Array.isArray(value)) return value.map((v) => flattenText(v, depth + 1)).join(" ");
  if (typeof value === "object") {
    return Object.values(value).map((v) => flattenText(v, depth + 1)).join(" ");
  }
  return "";
}
function labelList(value) {
  const raw = Array.isArray(value) ? value : value && typeof value === "object" ? Object.values(value) : value ? [value] : [];
  const out = [];
  for (const item of raw) {
    if (item == null) continue;
    if (typeof item === "string" || typeof item === "number") {
      const s = String(item).trim();
      if (s) out.push(s);
      continue;
    }
    if (typeof item === "object") {
      const o = item;
      const label = o.label ?? o.name ?? o.text ?? o.title ?? o.value ?? o.mistake ?? o.emotion;
      if (typeof label === "string" && label.trim()) out.push(label.trim());
      else {
        const nested = flattenText(o).trim();
        if (nested) out.push(nested.slice(0, 80));
      }
    }
  }
  return out;
}
function snippet(text, term, radius = 90) {
  const haystack = text.replace(/\s+/g, " ").trim();
  if (!haystack) return null;
  const idx = haystack.toLowerCase().indexOf(term.toLowerCase());
  if (idx < 0) return haystack.slice(0, radius * 2);
  const start = Math.max(0, idx - radius);
  const end = Math.min(haystack.length, idx + term.length + radius);
  return `${start > 0 ? "\u2026" : ""}${haystack.slice(start, end)}${end < haystack.length ? "\u2026" : ""}`;
}
function countOccurrences(text, term) {
  if (!term) return 0;
  const t = text.toLowerCase();
  const q = term.toLowerCase();
  let count = 0;
  let i = t.indexOf(q);
  while (i !== -1) {
    count += 1;
    i = t.indexOf(q, i + q.length);
  }
  return count;
}

// src/lib/mcp/tools/search-journal.ts
var SOURCES = ["trades", "notebook", "daily_plans", "weekly_plans"];
var search_journal_default = defineTool15({
  name: "search_journal",
  title: "Search the whole journal",
  description: "Free-text search across everything the signed-in user has written: trade notes and analysis, notebook entries, daily plans and weekly plans. Returns ranked results with snippets showing where the term matched.",
  inputSchema: {
    query: z14.string().min(1).describe("Text to search for, e.g. 'liquidity sweep' or 'revenge trade'."),
    sources: z14.string().optional().describe("Comma-separated subset of: trades, notebook, daily_plans, weekly_plans. Defaults to all."),
    from: z14.string().optional().describe("Start date (inclusive) in YYYY-MM-DD."),
    to: z14.string().optional().describe("End date (inclusive) in YYYY-MM-DD."),
    limit: z14.number().int().min(1).max(50).default(20).describe("Max results to return. Default 20.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, sources, from, to, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    const term = String(query ?? "").trim();
    if (!term) return failure("Query must not be empty.");
    const wanted = new Set(
      (sources ? String(sources).split(",").map((s) => s.trim()) : [...SOURCES]).filter(
        (s) => SOURCES.includes(s)
      )
    );
    if (wanted.size === 0) for (const s of SOURCES) wanted.add(s);
    const sb = supabaseForUser2(ctx);
    const uid = ctx.getUserId();
    const scope = (q, column) => {
      let out = q;
      if (from) out = out.gte(column, from);
      if (to) out = out.lte(column, to);
      return out;
    };
    const results = [];
    if (wanted.has("trades")) {
      const { data, error } = await scope(
        sb.from("trades").select("id,date,asset,setup,session,result,grade,profit_loss,notes,psychology,trade_analysis,confluences,mistakes,trade_journey").eq("user_id", uid),
        "date"
      ).order("date", { ascending: false }).limit(1e3);
      if (error) return failure(error.message);
      for (const row of data ?? []) {
        const text = [row.notes, flattenText(row.psychology), flattenText(row.trade_analysis), flattenText(row.confluences), flattenText(row.mistakes), flattenText(row.trade_journey)].join(" ");
        const hits = countOccurrences(text, term);
        if (hits) results.push({
          source: "trade",
          id: row.id,
          date: row.date,
          title: `${row.asset ?? "Trade"} \xB7 ${row.setup ?? "\u2014"} \xB7 ${row.result ?? ""}`.trim(),
          matches: hits,
          snippet: snippet(text, term),
          meta: { asset: row.asset, session: row.session, grade: row.grade, profit_loss: row.profit_loss }
        });
      }
    }
    if (wanted.has("notebook")) {
      const { data, error } = await scope(
        sb.from("notebook_entries").select("id,entry_id,date,pair,category,bias,journal,legacy_notes,legacy_key_levels").eq("user_id", uid),
        "date"
      ).order("date", { ascending: false }).limit(1e3);
      if (error) return failure(error.message);
      for (const row of data ?? []) {
        const text = [flattenText(row.journal), row.legacy_notes, row.legacy_key_levels, row.pair, row.category, row.bias].join(" ");
        const hits = countOccurrences(text, term);
        if (hits) results.push({
          source: "notebook",
          id: row.id,
          date: row.date,
          title: `${row.pair ?? "Note"} \xB7 ${row.category ?? ""}`.trim(),
          matches: hits,
          snippet: snippet(text, term),
          meta: { pair: row.pair, category: row.category, bias: row.bias }
        });
      }
    }
    if (wanted.has("daily_plans")) {
      const { data, error } = await scope(
        sb.from("daily_plans").select("id,date,daily_bias,session_focus,note,result_narrative,pairs,notes_journal,day_summary,reviewed").eq("user_id", uid),
        "date"
      ).order("date", { ascending: false }).limit(1e3);
      if (error) return failure(error.message);
      for (const row of data ?? []) {
        const text = [row.daily_bias, row.session_focus, row.note, row.result_narrative, flattenText(row.pairs), flattenText(row.notes_journal), flattenText(row.day_summary)].join(" ");
        const hits = countOccurrences(text, term);
        if (hits) results.push({
          source: "daily_plan",
          id: row.id,
          date: row.date,
          title: `Daily plan ${row.date}`,
          matches: hits,
          snippet: snippet(text, term),
          meta: { bias: row.daily_bias, reviewed: row.reviewed }
        });
      }
    }
    if (wanted.has("weekly_plans")) {
      const { data, error } = await scope(
        sb.from("weekly_plans").select("id,week_start,bias,levels,risk,goals,pair_analyses,news_result,observation,reviewed").eq("user_id", uid),
        "week_start"
      ).order("week_start", { ascending: false }).limit(500);
      if (error) return failure(error.message);
      for (const row of data ?? []) {
        const text = [row.bias, row.levels, row.risk, row.goals, row.news_result, flattenText(row.pair_analyses), flattenText(row.observation)].join(" ");
        const hits = countOccurrences(text, term);
        if (hits) results.push({
          source: "weekly_plan",
          id: row.id,
          date: row.week_start,
          title: `Weekly plan ${row.week_start}`,
          matches: hits,
          snippet: snippet(text, term),
          meta: { bias: row.bias, reviewed: row.reviewed }
        });
      }
    }
    results.sort((a, b) => b.matches - a.matches || String(b.date).localeCompare(String(a.date)));
    const take = limit ?? 20;
    return ok({
      query: term,
      sources: [...wanted],
      total_matches: results.length,
      returned: Math.min(take, results.length),
      results: results.slice(0, take)
    });
  }
});

// src/lib/mcp/tools/analyze-mistakes.ts
import { defineTool as defineTool16 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z15 } from "npm:zod@^3.25.76";
var analyze_mistakes_default = defineTool16({
  name: "analyze_mistakes",
  title: "Analyze recurring mistakes",
  description: "Find the signed-in user's most frequent trading mistakes / rule violations and quantify their cost: occurrences, win rate and net P/L of trades where each mistake appeared, plus recent examples.",
  inputSchema: {
    from: z15.string().optional().describe("Start date (inclusive) in YYYY-MM-DD."),
    to: z15.string().optional().describe("End date (inclusive) in YYYY-MM-DD."),
    days: z15.number().int().min(1).max(3650).optional().describe("Alternative to from/to: last N days."),
    limit: z15.number().int().min(1).max(50).default(15).describe("How many distinct mistakes to return. Default 15.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ from, to, days, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    const sb = supabaseForUser2(ctx);
    const start = from ?? (days ? new Date(Date.now() - days * 864e5).toISOString().slice(0, 10) : void 0);
    let q = sb.from("trades").select("id,date,asset,session,setup,grade,result,status,profit_loss,actual_rr,mistakes,psychology").eq("user_id", ctx.getUserId());
    if (start) q = q.gte("date", start);
    if (to) q = q.lte("date", to);
    const { data, error } = await q.order("date", { ascending: false });
    if (error) return failure(error.message);
    const rows = (data ?? []).filter(isExecuted);
    const buckets = /* @__PURE__ */ new Map();
    let cleanTrades = 0;
    let cleanPnl = 0;
    for (const row of rows) {
      const psych = row.psychology ?? {};
      const labels = [...labelList(row.mistakes), ...labelList(psych.mistakes)];
      const unique = [...new Set(labels.map((l) => l.trim()).filter(Boolean))];
      if (unique.length === 0) {
        cleanTrades += 1;
        cleanPnl += num(row.profit_loss);
        continue;
      }
      for (const label of unique) buckets.set(label, [...buckets.get(label) ?? [], row]);
    }
    const mistakes = [...buckets.entries()].map(([mistake, group]) => {
      const wins = group.filter((r) => isWin(r.result)).length;
      const losses = group.filter((r) => isLoss(r.result)).length;
      const netPnl = group.reduce((s, r) => s + num(r.profit_loss), 0);
      return {
        mistake,
        occurrences: group.length,
        wins,
        losses,
        win_rate_pct: group.length ? round(wins / group.length * 100) : 0,
        net_profit_loss: round(netPnl),
        average_profit_loss: round(netPnl / group.length),
        last_seen: group[0]?.date ?? null,
        examples: group.slice(0, 3).map((r) => ({
          id: r.id,
          date: r.date,
          asset: r.asset,
          setup: r.setup,
          result: r.result,
          profit_loss: round(num(r.profit_loss))
        }))
      };
    }).sort((a, b) => a.net_profit_loss - b.net_profit_loss || b.occurrences - a.occurrences).slice(0, limit ?? 15);
    const dirtyTrades = rows.length - cleanTrades;
    const dirtyPnl = rows.reduce((s, r) => s + num(r.profit_loss), 0) - cleanPnl;
    return ok({
      window: { from: start ?? null, to: to ?? null },
      executed_trades: rows.length,
      trades_with_mistakes: dirtyTrades,
      clean_trades: cleanTrades,
      mistake_rate_pct: rows.length ? round(dirtyTrades / rows.length * 100) : 0,
      net_profit_loss_clean: round(cleanPnl),
      net_profit_loss_with_mistakes: round(dirtyPnl),
      estimated_cost_of_mistakes: round(
        (cleanTrades ? cleanPnl / cleanTrades * dirtyTrades : 0) - dirtyPnl
      ),
      mistakes
    });
  }
});

// src/lib/mcp/tools/analyze-setups.ts
import { defineTool as defineTool17 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z16 } from "npm:zod@^3.25.76";
var DIMENSIONS = ["setup", "asset", "session", "grade", "direction", "market_condition", "timeframe"];
var analyze_setups_default = defineTool17({
  name: "analyze_setups",
  title: "Rank strongest and weakest setups",
  description: "Rank the signed-in user's setups (and optionally assets, sessions, grades, direction, market condition or timeframe) by net P/L, win rate, profit factor and expectancy, highlighting the strongest and weakest performers.",
  inputSchema: {
    dimension: z16.string().optional().describe("What to rank: setup (default), asset, session, grade, direction, market_condition or timeframe."),
    from: z16.string().optional().describe("Start date (inclusive) in YYYY-MM-DD."),
    to: z16.string().optional().describe("End date (inclusive) in YYYY-MM-DD."),
    days: z16.number().int().min(1).max(3650).optional().describe("Alternative to from/to: last N days."),
    min_trades: z16.number().int().min(1).max(100).default(3).describe("Ignore buckets with fewer trades than this. Default 3.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ dimension, from, to, days, min_trades }, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    const dim = DIMENSIONS.includes(String(dimension)) ? String(dimension) : "setup";
    const sb = supabaseForUser2(ctx);
    const start = from ?? (days ? new Date(Date.now() - days * 864e5).toISOString().slice(0, 10) : void 0);
    let q = sb.from("trades").select("date,asset,session,setup,grade,direction,market_condition,timeframe,result,status,profit_loss,actual_rr,planned_rr").eq("user_id", ctx.getUserId());
    if (start) q = q.gte("date", start);
    if (to) q = q.lte("date", to);
    const { data, error } = await q;
    if (error) return failure(error.message);
    const rows = data ?? [];
    const threshold = min_trades ?? 3;
    const all = groupPerformance(rows, dim);
    const qualified = all.filter((g) => g.trades >= threshold);
    const ranked = qualified.length ? qualified : all;
    return ok({
      dimension: dim,
      window: { from: start ?? null, to: to ?? null },
      min_trades: threshold,
      overall: computeMetrics(rows),
      ranking: all,
      strongest: ranked.slice(0, 3),
      weakest: ranked.slice(-3).reverse(),
      excluded_low_sample: all.filter((g) => g.trades < threshold).map((g) => g.label)
    });
  }
});

// src/lib/mcp/tools/analyze-psychology.ts
import { defineTool as defineTool18 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z17 } from "npm:zod@^3.25.76";
function bucketStats(group) {
  const wins = group.filter((r) => isWin(r.result)).length;
  const net = group.reduce((s, r) => s + num(r.profit_loss), 0);
  return {
    trades: group.length,
    wins,
    win_rate_pct: group.length ? round(wins / group.length * 100) : 0,
    net_profit_loss: round(net),
    average_profit_loss: group.length ? round(net / group.length) : 0
  };
}
var analyze_psychology_default = defineTool18({
  name: "analyze_psychology",
  title: "Analyze psychology and discipline",
  description: "Correlate the signed-in user's emotional state, discipline flags, trade grades and market sentiment with trading outcomes: which emotions precede wins or losses, and how discipline affects P/L.",
  inputSchema: {
    from: z17.string().optional().describe("Start date (inclusive) in YYYY-MM-DD."),
    to: z17.string().optional().describe("End date (inclusive) in YYYY-MM-DD."),
    days: z17.number().int().min(1).max(3650).optional().describe("Alternative to from/to: last N days.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ from, to, days }, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    const sb = supabaseForUser2(ctx);
    const start = from ?? (days ? new Date(Date.now() - days * 864e5).toISOString().slice(0, 10) : void 0);
    let q = sb.from("trades").select("id,date,asset,setup,grade,result,status,profit_loss,actual_rr,psychology,mistakes,market_sentiment,day_tags").eq("user_id", ctx.getUserId());
    if (start) q = q.gte("date", start);
    if (to) q = q.lte("date", to);
    const { data, error } = await q.order("date", { ascending: false });
    if (error) return failure(error.message);
    const rows = (data ?? []).filter(isExecuted);
    const emotions = /* @__PURE__ */ new Map();
    const tags = /* @__PURE__ */ new Map();
    const grades = /* @__PURE__ */ new Map();
    const disciplined = [];
    const undisciplined = [];
    for (const row of rows) {
      const psych = row.psychology ?? {};
      const labels = [
        ...labelList(psych.emotions),
        ...labelList(psych.emotion),
        ...labelList(psych.state),
        ...labelList(psych.feelings),
        ...labelList(psych.tags)
      ];
      for (const label of [...new Set(labels)]) emotions.set(label, [...emotions.get(label) ?? [], row]);
      for (const tag of [...new Set(labelList(row.day_tags))]) tags.set(tag, [...tags.get(tag) ?? [], row]);
      const g = String(row.grade ?? "Ungraded");
      grades.set(g, [...grades.get(g) ?? [], row]);
      const hasMistake = [...labelList(row.mistakes), ...labelList(psych.mistakes)].length > 0;
      const followedPlan = psych.followedPlan ?? psych.followed_plan ?? psych.discipline;
      const brokeRules = followedPlan === false || hasMistake;
      (brokeRules ? undisciplined : disciplined).push(row);
    }
    const rank = (m) => [...m.entries()].map(([label, group]) => ({ label, ...bucketStats(group) })).sort((a, b) => b.net_profit_loss - a.net_profit_loss);
    const sentiment = rows.filter((r) => Number.isFinite(Number(r.market_sentiment)));
    const sentimentBuckets = /* @__PURE__ */ new Map();
    for (const row of sentiment) {
      const v = Number(row.market_sentiment);
      const key = v >= 7 ? "high (7-10)" : v >= 4 ? "neutral (4-6)" : "low (0-3)";
      sentimentBuckets.set(key, [...sentimentBuckets.get(key) ?? [], row]);
    }
    return ok({
      window: { from: start ?? null, to: to ?? null },
      executed_trades: rows.length,
      emotions: rank(emotions),
      best_emotional_states: rank(emotions).slice(0, 3),
      worst_emotional_states: rank(emotions).slice(-3).reverse(),
      day_tags: rank(tags),
      by_grade: rank(grades),
      market_sentiment: [...sentimentBuckets.entries()].map(([label, group]) => ({ label, ...bucketStats(group) })),
      discipline: {
        followed_plan: bucketStats(disciplined),
        broke_rules: bucketStats(undisciplined),
        discipline_rate_pct: rows.length ? round(disciplined.length / rows.length * 100) : 0
      }
    });
  }
});

// src/lib/mcp/tools/get-consistency-report.ts
import { defineTool as defineTool19 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z18 } from "npm:zod@^3.25.76";
function checklistPct(sections) {
  const list = Array.isArray(sections) ? sections : [];
  const total = list.reduce((a, s) => a + (s.items?.length ?? 0), 0);
  const done = list.reduce((a, s) => a + (s.items ?? []).filter((i) => i.done).length, 0);
  return total ? done / total * 100 : 0;
}
var get_consistency_report_default = defineTool19({
  name: "get_consistency_report",
  title: "Get consistency and discipline report",
  description: "Measure the signed-in user's process consistency: planning coverage (days planned vs traded), checklist completion, plan review rate, risk/size consistency, overtrading days and mistake-free rate.",
  inputSchema: {
    days: z18.number().int().min(7).max(365).default(30).describe("Look-back window in days. Default 30.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ days }, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    const sb = supabaseForUser2(ctx);
    const uid = ctx.getUserId();
    const window = days ?? 30;
    const since = new Date(Date.now() - window * 864e5).toISOString().slice(0, 10);
    const [tradesRes, plansRes, checklistRes] = await Promise.all([
      sb.from("trades").select("id,date,result,status,profit_loss,quantity,actual_rr,planned_rr,mistakes,psychology,setup,grade").eq("user_id", uid).gte("date", since),
      sb.from("daily_plans").select("date,reviewed,max_trades,risk_limit,daily_bias,pair_count").eq("user_id", uid).gte("date", since),
      sb.from("trading_checklists").select("date,sections").eq("user_id", uid).gte("date", since)
    ]);
    if (tradesRes.error) return failure(tradesRes.error.message);
    if (plansRes.error) return failure(plansRes.error.message);
    if (checklistRes.error) return failure(checklistRes.error.message);
    const trades = (tradesRes.data ?? []).filter(isExecuted);
    const plans = plansRes.data ?? [];
    const checklists = checklistRes.data ?? [];
    const plannedDates = new Set(plans.map((p) => String(p.date)));
    const tradedDates = new Set(trades.map((t) => String(t.date)));
    const plannedAndTraded = [...tradedDates].filter((d) => plannedDates.has(d));
    const perDay = /* @__PURE__ */ new Map();
    for (const t of trades) perDay.set(String(t.date), [...perDay.get(String(t.date)) ?? [], t]);
    const planLimit = new Map(plans.map((p) => [String(p.date), Number(p.max_trades) || null]));
    const overtradingDays = [...perDay.entries()].filter(([date2, list]) => (planLimit.get(date2) ?? 2) < list.length).map(([date2, list]) => ({ date: date2, trades: list.length, limit: planLimit.get(date2) ?? 2 }));
    const sizes = trades.map((t) => num(t.quantity)).filter((v) => v > 0);
    const mean = sizes.length ? sizes.reduce((a, b) => a + b, 0) / sizes.length : 0;
    const variance = sizes.length ? sizes.reduce((a, b) => a + (b - mean) ** 2, 0) / sizes.length : 0;
    const stdev = Math.sqrt(variance);
    const cleanTrades = trades.filter((t) => {
      const psych = t.psychology ?? {};
      return [...labelList(t.mistakes), ...labelList(psych.mistakes)].length === 0;
    });
    const checklistScores = checklists.map((c) => checklistPct(c.sections));
    const avgChecklist = checklistScores.length ? checklistScores.reduce((a, b) => a + b, 0) / checklistScores.length : 0;
    return ok({
      window: { days: window, from: since, to: (/* @__PURE__ */ new Date()).toISOString().slice(0, 10) },
      planning: {
        days_planned: plannedDates.size,
        days_traded: tradedDates.size,
        traded_with_plan: plannedAndTraded.length,
        plan_coverage_pct: tradedDates.size ? round(plannedAndTraded.length / tradedDates.size * 100) : 0,
        plans_reviewed: plans.filter((p) => p.reviewed).length,
        plan_review_rate_pct: plans.length ? round(plans.filter((p) => p.reviewed).length / plans.length * 100) : 0
      },
      checklist: {
        days_logged: checklists.length,
        logging_rate_pct: round(checklists.length / window * 100),
        average_completion_pct: round(avgChecklist),
        perfect_days: checklistScores.filter((s) => s >= 99.9).length
      },
      execution: {
        executed_trades: trades.length,
        trades_per_trading_day: tradedDates.size ? round(trades.length / tradedDates.size, 2) : 0,
        overtrading_days: overtradingDays.length,
        overtrading_detail: overtradingDays,
        mistake_free_trades: cleanTrades.length,
        mistake_free_rate_pct: trades.length ? round(cleanTrades.length / trades.length * 100) : 0,
        graded_trades_pct: trades.length ? round(trades.filter((t) => t.grade).length / trades.length * 100) : 0
      },
      risk_consistency: {
        average_position_size: round(mean, 4),
        position_size_stdev: round(stdev, 4),
        size_variation_pct: mean ? round(stdev / mean * 100) : 0,
        rr_discipline_pct: trades.length ? round(trades.filter((t) => Number(t.planned_rr) > 0).length / trades.length * 100) : 0
      },
      consistency_score: round(
        0.3 * (tradedDates.size ? plannedAndTraded.length / tradedDates.size * 100 : 0) + 0.3 * avgChecklist + 0.25 * (trades.length ? cleanTrades.length / trades.length * 100 : 0) + 0.15 * Math.max(0, 100 - (mean ? stdev / mean * 100 : 0))
      )
    });
  }
});

// src/lib/mcp/tools/get-monthly-summary.ts
import { defineTool as defineTool20 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z19 } from "npm:zod@^3.25.76";
function monthBounds(month) {
  const key = month && /^\d{4}-\d{2}$/.test(month) ? month : (/* @__PURE__ */ new Date()).toISOString().slice(0, 7);
  const [y, m] = key.split("-").map(Number);
  const end = new Date(Date.UTC(y, m, 0)).toISOString().slice(0, 10);
  return { month: key, from: `${key}-01`, to: end };
}
var get_monthly_summary_default = defineTool20({
  name: "get_monthly_summary",
  title: "Get monthly trading summary",
  description: "Full synthesis of one calendar month for the signed-in user: metrics, equity curve, best/worst days, setup and session breakdowns, top mistakes, and plan/checklist adherence.",
  inputSchema: {
    month: z19.string().optional().describe("Month in YYYY-MM. Defaults to the current month.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ month }, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    const sb = supabaseForUser2(ctx);
    const uid = ctx.getUserId();
    const { month: key, from, to } = monthBounds(month);
    const [tradesRes, plansRes, checklistRes] = await Promise.all([
      sb.from("trades").select("id,date,asset,session,setup,grade,result,status,direction,profit_loss,actual_rr,planned_rr,mistakes,psychology,notes").eq("user_id", uid).gte("date", from).lte("date", to).order("date", { ascending: true }),
      sb.from("daily_plans").select("date,reviewed,daily_bias,note").eq("user_id", uid).gte("date", from).lte("date", to),
      sb.from("trading_checklists").select("date,sections").eq("user_id", uid).gte("date", from).lte("date", to)
    ]);
    if (tradesRes.error) return failure(tradesRes.error.message);
    if (plansRes.error) return failure(plansRes.error.message);
    if (checklistRes.error) return failure(checklistRes.error.message);
    const rows = tradesRes.data ?? [];
    const executed = rows.filter(isExecuted);
    const byDay = /* @__PURE__ */ new Map();
    for (const t of executed) byDay.set(String(t.date), [...byDay.get(String(t.date)) ?? [], t]);
    const days = [...byDay.entries()].map(([date2, list]) => ({
      date: date2,
      trades: list.length,
      net_profit_loss: round(list.reduce((s, r) => s + num(r.profit_loss), 0))
    })).sort((a, b) => a.date.localeCompare(b.date));
    const sortedByPnl = [...days].sort((a, b) => b.net_profit_loss - a.net_profit_loss);
    const mistakeCounts = /* @__PURE__ */ new Map();
    for (const t of executed) {
      const psych = t.psychology ?? {};
      for (const label of /* @__PURE__ */ new Set([...labelList(t.mistakes), ...labelList(psych.mistakes)])) {
        mistakeCounts.set(label, (mistakeCounts.get(label) ?? 0) + 1);
      }
    }
    let streakWin = 0, bestWinStreak = 0, streakLoss = 0, worstLossStreak = 0;
    for (const d of days) {
      if (d.net_profit_loss > 0) {
        streakWin += 1;
        streakLoss = 0;
      } else if (d.net_profit_loss < 0) {
        streakLoss += 1;
        streakWin = 0;
      }
      bestWinStreak = Math.max(bestWinStreak, streakWin);
      worstLossStreak = Math.max(worstLossStreak, streakLoss);
    }
    const checklists = checklistRes.data ?? [];
    const checklistPct2 = checklists.map((c) => {
      const list = Array.isArray(c.sections) ? c.sections : [];
      const total = list.reduce((a, s) => a + (s.items?.length ?? 0), 0);
      const done = list.reduce((a, s) => a + (s.items ?? []).filter((i) => i.done).length, 0);
      return total ? done / total * 100 : 0;
    });
    return ok({
      month: key,
      window: { from, to },
      metrics: computeMetrics(rows),
      equity: equityCurve(rows),
      trading_days: days.length,
      green_days: days.filter((d) => d.net_profit_loss > 0).length,
      red_days: days.filter((d) => d.net_profit_loss < 0).length,
      best_day: sortedByPnl[0] ?? null,
      worst_day: sortedByPnl[sortedByPnl.length - 1] ?? null,
      longest_green_streak_days: bestWinStreak,
      longest_red_streak_days: worstLossStreak,
      daily_pnl: days,
      by_setup: groupPerformance(rows, "setup"),
      by_session: groupPerformance(rows, "session"),
      by_asset: groupPerformance(rows, "asset"),
      top_mistakes: [...mistakeCounts.entries()].map(([mistake, count]) => ({ mistake, count })).sort((a, b) => b.count - a.count).slice(0, 10),
      routine: {
        plans_created: (plansRes.data ?? []).length,
        plans_reviewed: (plansRes.data ?? []).filter((p) => p.reviewed).length,
        checklist_days: checklists.length,
        checklist_average_pct: checklistPct2.length ? round(checklistPct2.reduce((a, b) => a + b, 0) / checklistPct2.length) : 0
      }
    });
  }
});

// src/lib/mcp/tools/get-weekly-report.ts
import { defineTool as defineTool21 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z20 } from "npm:zod@^3.25.76";
var get_weekly_report_default = defineTool21({
  name: "get_weekly_report",
  title: "Get weekly trading report",
  description: "Synthesis of one trading week for the signed-in user: metrics, day-by-day P/L, setup/session breakdown, mistakes, plus the weekly plan (bias, goals, pair analyses) and its review status.",
  inputSchema: {
    week_start: z20.string().optional().describe("Monday of the week in YYYY-MM-DD. Defaults to the current week.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ week_start }, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    const sb = supabaseForUser2(ctx);
    const uid = ctx.getUserId();
    const start = weekStart(week_start ?? (/* @__PURE__ */ new Date()).toISOString().slice(0, 10));
    const end = new Date(Date.parse(`${start}T00:00:00Z`) + 6 * 864e5).toISOString().slice(0, 10);
    const [tradesRes, weeklyRes, plansRes, checklistRes] = await Promise.all([
      sb.from("trades").select("id,date,asset,session,setup,grade,result,status,direction,profit_loss,actual_rr,planned_rr,mistakes,psychology,notes").eq("user_id", uid).gte("date", start).lte("date", end).order("date", { ascending: true }),
      sb.from("weekly_plans").select("*").eq("user_id", uid).eq("week_start", start).maybeSingle(),
      sb.from("daily_plans").select("date,daily_bias,reviewed,note").eq("user_id", uid).gte("date", start).lte("date", end),
      sb.from("trading_checklists").select("date,sections").eq("user_id", uid).gte("date", start).lte("date", end)
    ]);
    if (tradesRes.error) return failure(tradesRes.error.message);
    if (plansRes.error) return failure(plansRes.error.message);
    if (checklistRes.error) return failure(checklistRes.error.message);
    const rows = tradesRes.data ?? [];
    const executed = rows.filter(isExecuted);
    const byDay = /* @__PURE__ */ new Map();
    for (const t of executed) byDay.set(String(t.date), [...byDay.get(String(t.date)) ?? [], t]);
    const days = [...Array(7)].map((_, i) => {
      const date2 = new Date(Date.parse(`${start}T00:00:00Z`) + i * 864e5).toISOString().slice(0, 10);
      const list = byDay.get(date2) ?? [];
      return {
        date: date2,
        weekday: ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"][i],
        trades: list.length,
        net_profit_loss: round(list.reduce((s, r) => s + num(r.profit_loss), 0))
      };
    });
    const mistakeCounts = /* @__PURE__ */ new Map();
    for (const t of executed) {
      const psych = t.psychology ?? {};
      for (const label of /* @__PURE__ */ new Set([...labelList(t.mistakes), ...labelList(psych.mistakes)])) {
        mistakeCounts.set(label, (mistakeCounts.get(label) ?? 0) + 1);
      }
    }
    const checklists = checklistRes.data ?? [];
    return ok({
      week_start: start,
      week_end: end,
      metrics: computeMetrics(rows),
      days,
      by_setup: groupPerformance(rows, "setup"),
      by_session: groupPerformance(rows, "session"),
      by_asset: groupPerformance(rows, "asset"),
      top_mistakes: [...mistakeCounts.entries()].map(([mistake, count]) => ({ mistake, count })).sort((a, b) => b.count - a.count).slice(0, 10),
      weekly_plan: weeklyRes.error ? null : weeklyRes.data ?? null,
      daily_plans: plansRes.data ?? [],
      checklist_days: checklists.length,
      notable_trades: executed.slice().sort((a, b) => Math.abs(num(b.profit_loss)) - Math.abs(num(a.profit_loss))).slice(0, 5).map((t) => ({
        id: t.id,
        date: t.date,
        asset: t.asset,
        setup: t.setup,
        result: t.result,
        profit_loss: round(num(t.profit_loss)),
        actual_rr: t.actual_rr,
        grade: t.grade
      }))
    });
  }
});

// src/lib/mcp/tools/create-trade.ts
import { defineTool as defineTool22 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z21 } from "npm:zod@^3.25.76";
var TRADE_WRITE_FIELDS = {
  date: z21.string().describe("Trade date in YYYY-MM-DD."),
  asset: z21.string().describe("Pair/asset symbol, e.g. XAUUSD."),
  direction: z21.string().optional().describe("Long or Short."),
  market: z21.string().optional().describe("Market, e.g. Forex, Crypto, Indices."),
  session: z21.string().optional().describe("Session, e.g. London, New York."),
  setup: z21.string().optional().describe("Setup name."),
  timeframe: z21.string().optional().describe("Execution timeframe, e.g. 5m, 15m, 1H."),
  market_condition: z21.string().optional().describe("Market condition, e.g. Trending, Ranging."),
  order_type: z21.string().optional().describe("Order type, e.g. Market, Limit, Stop."),
  entry_time: z21.string().optional().describe("Entry time, e.g. 09:35."),
  exit_time: z21.string().optional().describe("Exit time, e.g. 11:05."),
  quantity: z21.number().optional().describe("Position size / lots."),
  entry_price: z21.number().optional().describe("Entry price."),
  stop_loss: z21.number().optional().describe("Stop-loss price."),
  take_profit: z21.number().optional().describe("Take-profit price."),
  exit_price: z21.number().optional().describe("Exit price."),
  result: z21.string().optional().describe("Win, Loss, Breakeven, Untriggered Setup or Cancelled."),
  status: z21.string().optional().describe("Complete or Draft. Defaults to Complete."),
  planned_rr: z21.number().optional().describe("Planned risk/reward."),
  actual_rr: z21.number().optional().describe("Achieved risk/reward."),
  pips: z21.number().optional().describe("Pips gained or lost."),
  profit_loss: z21.number().optional().describe("Net P/L in account currency."),
  fees: z21.number().optional().describe("Fees/commission."),
  grade: z21.string().optional().describe("Execution grade: A+, A, B, C."),
  notes: z21.string().optional().describe("Free-text notes about the trade."),
  chart_link: z21.string().optional().describe("External chart link (e.g. TradingView)."),
  mistakes: z21.array(z21.string()).optional().describe("List of mistakes / rule violations."),
  confluences: z21.array(z21.string()).optional().describe("List of confluences supporting the trade.")
};
function compact(obj) {
  return Object.fromEntries(Object.entries(obj).filter(([, v]) => v !== void 0));
}
var create_trade_default = defineTool22({
  name: "create_trade",
  title: "Create a trade",
  description: "Log a new trade in the signed-in user's journal. Only `date` and `asset` are required; every other field is optional. Returns the created trade record including its generated id.",
  inputSchema: TRADE_WRITE_FIELDS,
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    const { mistakes, confluences, ...rest } = input;
    const id = typeof globalThis.crypto?.randomUUID === "function" ? globalThis.crypto.randomUUID() : `trade-${Date.now()}-${Math.random().toString(36).slice(2, 10)}`;
    const payload = compact({
      ...rest,
      id,
      user_id: ctx.getUserId(),
      status: rest.status ?? "Complete",
      mistakes: mistakes ?? void 0,
      confluences: confluences ?? void 0
    });
    const sb = supabaseForUser2(ctx);
    const { data, error } = await sb.from("trades").insert(payload).select().maybeSingle();
    if (error) return failure(error.message);
    return ok({ created: true, trade: data });
  }
});

// src/lib/mcp/tools/update-trade.ts
import { defineTool as defineTool23 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z22 } from "npm:zod@^3.25.76";
var { date, asset, ...optionalFields } = TRADE_WRITE_FIELDS;
var update_trade_default = defineTool23({
  name: "update_trade",
  title: "Update a trade",
  description: "Update fields on an existing trade owned by the signed-in user. Only the fields you pass are changed; omitted fields keep their current values.",
  inputSchema: {
    id: z22.string().min(1).describe("Id of the trade to update (from list_trades / search_trades)."),
    date: date.optional(),
    asset: asset.optional(),
    ...optionalFields
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: true, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    const { id, ...rest } = input;
    const patch = compact(rest);
    if (Object.keys(patch).length === 0) return failure("Provide at least one field to update.");
    const sb = supabaseForUser2(ctx);
    const { data, error } = await sb.from("trades").update(patch).eq("id", id).eq("user_id", ctx.getUserId()).select().maybeSingle();
    if (error) return failure(error.message);
    if (!data) return failure(`No trade found with id "${id}".`);
    return ok({ updated: true, fields: Object.keys(patch), trade: data });
  }
});

// src/lib/mcp/tools/delete-trade.ts
import { defineTool as defineTool24 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z23 } from "npm:zod@^3.25.76";
var delete_trade_default = defineTool24({
  name: "delete_trade",
  title: "Delete a trade",
  description: "Permanently delete one of the signed-in user's trades. Requires `confirm: true` so it can never happen by accident. Ask the user before calling this.",
  inputSchema: {
    id: z23.string().min(1).describe("Id of the trade to delete."),
    confirm: z23.boolean().describe("Must be true. Explicit confirmation that the trade should be deleted.")
  },
  annotations: { readOnlyHint: false, destructiveHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ id, confirm }, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    if (!confirm) return failure("Deletion not confirmed. Call again with confirm: true after the user agrees.");
    const sb = supabaseForUser2(ctx);
    const { data, error } = await sb.from("trades").delete().eq("id", id).eq("user_id", ctx.getUserId()).select("id,date,asset,result,profit_loss").maybeSingle();
    if (error) return failure(error.message);
    if (!data) return failure(`No trade found with id "${id}".`);
    return ok({ deleted: true, trade: data });
  }
});

// src/lib/mcp/tools/upsert-daily-plan.ts
import { defineTool as defineTool25 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z24 } from "npm:zod@^3.25.76";
var upsert_daily_plan_default = defineTool25({
  name: "upsert_daily_plan",
  title: "Create or update a daily plan",
  description: "Create or update the signed-in user's daily plan for a date. Only the fields you pass are written; existing pair analyses and journal content are preserved unless explicitly replaced.",
  inputSchema: {
    date: z24.string().describe("Plan date in YYYY-MM-DD."),
    daily_bias: z24.string().optional().describe("Directional bias for the day, e.g. Bullish, Bearish, Neutral."),
    session_focus: z24.string().optional().describe("Session the user intends to trade."),
    max_trades: z24.number().int().min(0).max(50).optional().describe("Maximum number of trades allowed for the day."),
    risk_limit: z24.string().optional().describe("Risk limit for the day, e.g. '1%'."),
    note: z24.string().optional().describe("Free-text plan note."),
    result_narrative: z24.string().optional().describe("End-of-day narrative of what actually happened."),
    took_trades: z24.boolean().optional().describe("Whether the user traded that day."),
    reviewed: z24.boolean().optional().describe("Mark the plan as reviewed.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: true, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    const { date: date2, ...rest } = input;
    const patch = compact(rest);
    const sb = supabaseForUser2(ctx);
    const uid = ctx.getUserId();
    const { data: existing, error: readError } = await sb.from("daily_plans").select("id").eq("user_id", uid).eq("date", date2).maybeSingle();
    if (readError) return failure(readError.message);
    if (existing) {
      if (Object.keys(patch).length === 0) return failure("Provide at least one field to update.");
      const { data: data2, error: error2 } = await sb.from("daily_plans").update(patch).eq("id", existing.id).eq("user_id", uid).select().maybeSingle();
      if (error2) return failure(error2.message);
      return ok({ created: false, updated: true, fields: Object.keys(patch), plan: data2 });
    }
    const id = typeof globalThis.crypto?.randomUUID === "function" ? globalThis.crypto.randomUUID() : `plan-${date2}-${Math.random().toString(36).slice(2, 10)}`;
    const { data, error } = await sb.from("daily_plans").insert({ id, user_id: uid, date: date2, ...patch }).select().maybeSingle();
    if (error) return failure(error.message);
    return ok({ created: true, updated: false, plan: data });
  }
});

// src/lib/mcp/tools/upsert-weekly-plan.ts
import { defineTool as defineTool26 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z25 } from "npm:zod@^3.25.76";
var upsert_weekly_plan_default = defineTool26({
  name: "upsert_weekly_plan",
  title: "Create or update a weekly plan",
  description: "Create or update the signed-in user's weekly plan. Only the fields you pass are written; pair analyses and news items are preserved unless explicitly replaced.",
  inputSchema: {
    week_start: z25.string().optional().describe("Monday of the week in YYYY-MM-DD. Defaults to the current week."),
    bias: z25.string().optional().describe("Weekly directional bias."),
    levels: z25.string().optional().describe("Key levels to watch."),
    risk: z25.string().optional().describe("Risk plan for the week."),
    goals: z25.string().optional().describe("Goals for the week."),
    news_result: z25.string().optional().describe("How the week's news events played out."),
    reviewed: z25.boolean().optional().describe("Mark the weekly plan as reviewed.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: true, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    const { week_start, ...rest } = input;
    const start = weekStart(week_start ?? (/* @__PURE__ */ new Date()).toISOString().slice(0, 10));
    const patch = compact(rest);
    const sb = supabaseForUser2(ctx);
    const uid = ctx.getUserId();
    const { data: existing, error: readError } = await sb.from("weekly_plans").select("id").eq("user_id", uid).eq("week_start", start).maybeSingle();
    if (readError) return failure(readError.message);
    if (existing) {
      if (Object.keys(patch).length === 0) return failure("Provide at least one field to update.");
      const { data: data2, error: error2 } = await sb.from("weekly_plans").update(patch).eq("id", existing.id).eq("user_id", uid).select().maybeSingle();
      if (error2) return failure(error2.message);
      return ok({ week_start: start, created: false, updated: true, fields: Object.keys(patch), plan: data2 });
    }
    const id = typeof globalThis.crypto?.randomUUID === "function" ? globalThis.crypto.randomUUID() : `weekly-${start}-${Math.random().toString(36).slice(2, 10)}`;
    const { data, error } = await sb.from("weekly_plans").insert({ id, user_id: uid, week_start: start, ...patch }).select().maybeSingle();
    if (error) return failure(error.message);
    return ok({ week_start: start, created: true, updated: false, plan: data });
  }
});

// src/lib/mcp/tools/create-notebook-entry.ts
import { defineTool as defineTool27 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z26 } from "npm:zod@^3.25.76";
var create_notebook_entry_default = defineTool27({
  name: "create_notebook_entry",
  title: "Create or update a notebook entry",
  description: "Write a journal / notebook entry for the signed-in user (analysis, reflection, lessons). Pass `entry_id` of an existing entry to update it instead of creating a new one.",
  inputSchema: {
    text: z26.string().min(1).describe("The journal text to store."),
    date: z26.string().optional().describe("Entry date in YYYY-MM-DD. Defaults to today."),
    pair: z26.string().optional().describe("Related pair/asset, e.g. XAUUSD."),
    category: z26.string().optional().describe("Notebook category, e.g. Analysis, Lesson, Review."),
    bias: z26.string().optional().describe("Directional bias for the note."),
    entry_id: z26.string().optional().describe("Existing entry_id to update instead of creating a new entry.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: false },
  handler: async ({ text, date: date2, pair, category, bias, entry_id }, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    const sb = supabaseForUser2(ctx);
    const uid = ctx.getUserId();
    const day = date2 ?? (/* @__PURE__ */ new Date()).toISOString().slice(0, 10);
    const journal = { text: String(text), media: [] };
    if (entry_id) {
      const { data: data2, error: error2 } = await sb.from("notebook_entries").update({
        journal,
        ...date2 ? { date: day } : {},
        ...pair ? { pair } : {},
        ...category ? { category } : {},
        ...bias ? { bias } : {}
      }).eq("entry_id", entry_id).eq("user_id", uid).select().maybeSingle();
      if (error2) return failure(error2.message);
      if (!data2) return failure(`No notebook entry found with entry_id "${entry_id}".`);
      return ok({ created: false, updated: true, entry: data2 });
    }
    const newId = typeof globalThis.crypto?.randomUUID === "function" ? globalThis.crypto.randomUUID() : `note-${Date.now()}-${Math.random().toString(36).slice(2, 10)}`;
    const { data, error } = await sb.from("notebook_entries").insert({
      user_id: uid,
      entry_id: newId,
      date: day,
      pair: pair ?? "",
      category: category ?? "",
      bias: bias ?? "",
      journal
    }).select().maybeSingle();
    if (error) return failure(error.message);
    return ok({ created: true, updated: false, entry: data });
  }
});

// src/lib/mcp/tools/update-checklist.ts
import { defineTool as defineTool28 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z27 } from "npm:zod@^3.25.76";
var itemLabel = (i) => String(i.label ?? i.text ?? i.title ?? "");
var sectionLabel = (s) => String(s.title ?? s.name ?? "");
var update_checklist_default = defineTool28({
  name: "update_checklist",
  title: "Tick or untick checklist items",
  description: "Mark items on the signed-in user's daily trading checklist as done or not done. Match items by id or by (case-insensitive) label text. Use get_checklist first to see the available items.",
  inputSchema: {
    date: z27.string().optional().describe("Checklist date in YYYY-MM-DD. Defaults to today."),
    items: z27.array(
      z27.object({
        match: z27.string().min(1).describe("Item id or label text to match."),
        done: z27.boolean().describe("New completion state for the item."),
        section: z27.string().optional().describe("Optional section id or title to disambiguate.")
      })
    ).min(1).describe("Items to update.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: true, openWorldHint: false },
  handler: async ({ date: date2, items }, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    const sb = supabaseForUser2(ctx);
    const uid = ctx.getUserId();
    const day = date2 ?? (/* @__PURE__ */ new Date()).toISOString().slice(0, 10);
    const { data: row, error } = await sb.from("trading_checklists").select("id,date,sections").eq("user_id", uid).eq("date", day).maybeSingle();
    if (error) return failure(error.message);
    if (!row) return failure(`No checklist exists for ${day}. Open the Trading Checklist page for that day first.`);
    const sections = Array.isArray(row.sections) ? row.sections : [];
    const applied = [];
    const missed = [];
    for (const req of items) {
      const needle = req.match.trim().toLowerCase();
      const scope = req.section ? sections.filter(
        (s) => String(s.id ?? "").toLowerCase() === req.section.trim().toLowerCase() || sectionLabel(s).toLowerCase() === req.section.trim().toLowerCase()
      ) : sections;
      let hit = false;
      for (const section of scope) {
        for (const item of section.items ?? []) {
          const matches = String(item.id ?? "").toLowerCase() === needle || itemLabel(item).toLowerCase() === needle || itemLabel(item).toLowerCase().includes(needle);
          if (!matches) continue;
          item.done = req.done;
          hit = true;
          applied.push({ match: req.match, item: itemLabel(item), section: sectionLabel(section), done: req.done });
          break;
        }
        if (hit) break;
      }
      if (!hit) missed.push(req.match);
    }
    if (applied.length === 0) return failure(`No checklist items matched: ${missed.join(", ")}.`);
    const { data: saved, error: saveError } = await sb.from("trading_checklists").update({ sections }).eq("id", row.id).eq("user_id", uid).select("date,sections").maybeSingle();
    if (saveError) return failure(saveError.message);
    const list = Array.isArray(saved?.sections) ? saved.sections : [];
    const total = list.reduce((a, s) => a + (s.items?.length ?? 0), 0);
    const done = list.reduce((a, s) => a + (s.items ?? []).filter((i) => i.done).length, 0);
    return ok({
      date: day,
      updated: applied,
      unmatched: missed,
      progress: {
        total_items: total,
        completed_items: done,
        completion_pct: total ? round(done / total * 100) : 0
      }
    });
  }
});

// src/lib/mcp/tools/get-media-url.ts
import { defineTool as defineTool29 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z28 } from "npm:zod@^3.25.76";
var get_media_url_default = defineTool29({
  name: "get_media_url",
  title: "Get a fresh signed media URL",
  description: "Mint short-lived signed URLs for the signed-in user's journal media (chart screenshots, attachments). Accepts storage paths or stale/expired journal-media URLs and returns currently valid links a client can open or fetch.",
  inputSchema: {
    paths: z28.array(z28.string().min(1)).min(1).max(50).describe("Storage paths or existing journal-media URLs (e.g. from list_media or a trade's prediction_image)."),
    expires_in: z28.number().int().min(60).max(86400).default(3600).describe("Signed URL lifetime in seconds (60-86400). Default 3600.")
  },
  annotations: { readOnlyHint: true, idempotentHint: false, openWorldHint: false },
  handler: async ({ paths, expires_in }, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    const sb = supabaseForUser2(ctx);
    const ttl = expires_in ?? 3600;
    const resolved = paths.map((p) => ({ input: p, path: storagePath(p) }));
    const valid = resolved.filter((r) => r.path);
    if (valid.length === 0) return failure("None of the supplied values point at journal media.");
    const { data, error } = await sb.storage.from(BUCKET).createSignedUrls(valid.map((v) => v.path), ttl);
    if (error) return failure(error.message);
    const byPath = new Map((data ?? []).map((d) => [String(d.path), d]));
    return ok({
      expires_in: ttl,
      media: valid.map((v) => {
        const entry = byPath.get(v.path);
        return {
          input: v.input,
          path: v.path,
          signed_url: entry?.signedUrl ?? null,
          error: entry?.error ?? (entry?.signedUrl ? null : "Could not sign this path.")
        };
      }),
      skipped: resolved.filter((r) => !r.path).map((r) => r.input)
    });
  }
});

// src/lib/mcp/tools/list-media.ts
import { defineTool as defineTool30 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z29 } from "npm:zod@^3.25.76";
var list_media_default = defineTool30({
  name: "list_media",
  title: "List journal media attachments",
  description: "List the media (chart screenshots and attachments) referenced by the signed-in user's trades, daily plans and notebook entries, optionally within a date range or for one trade. Set `sign: true` to also return short-lived signed URLs.",
  inputSchema: {
    trade_id: z29.string().optional().describe("Only media attached to this trade."),
    from: z29.string().optional().describe("Start date (inclusive) in YYYY-MM-DD."),
    to: z29.string().optional().describe("End date (inclusive) in YYYY-MM-DD."),
    sources: z29.string().optional().describe("Comma-separated subset of: trades, notebook, daily_plans. Defaults to all."),
    sign: z29.boolean().default(false).describe("Also mint signed URLs for each item. Default false."),
    expires_in: z29.number().int().min(60).max(86400).default(3600).describe("Signed URL lifetime in seconds when sign is true."),
    limit: z29.number().int().min(1).max(100).default(50).describe("Max media items to return. Default 50.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ trade_id, from, to, sources, sign, expires_in, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    const sb = supabaseForUser2(ctx);
    const uid = ctx.getUserId();
    const wanted = new Set(
      (sources ? String(sources).split(",").map((s) => s.trim()) : ["trades", "notebook", "daily_plans"]).filter(
        (s) => ["trades", "notebook", "daily_plans"].includes(s)
      )
    );
    if (wanted.size === 0) for (const s of ["trades", "notebook", "daily_plans"]) wanted.add(s);
    const items = [];
    if (wanted.has("trades")) {
      let q = sb.from("trades").select("id,date,asset,prediction_image,execution_image,trade_journey,trade_analysis").eq("user_id", uid);
      if (trade_id) q = q.eq("id", trade_id);
      if (from) q = q.gte("date", from);
      if (to) q = q.lte("date", to);
      const { data, error } = await q.order("date", { ascending: false }).limit(500);
      if (error) return failure(error.message);
      for (const row of data ?? []) {
        for (const field of ["prediction_image", "execution_image"]) {
          const p = storagePath(row[field]);
          if (p) items.push({ source: "trade", id: row.id, date: row.date, field, path: p });
        }
        for (const p of collectPaths([row.trade_journey, row.trade_analysis])) {
          items.push({ source: "trade", id: row.id, date: row.date, field: "journey", path: p });
        }
      }
    }
    if (!trade_id && wanted.has("notebook")) {
      let q = sb.from("notebook_entries").select("id,entry_id,date,pair,journal,legacy_image").eq("user_id", uid);
      if (from) q = q.gte("date", from);
      if (to) q = q.lte("date", to);
      const { data, error } = await q.order("date", { ascending: false }).limit(500);
      if (error) return failure(error.message);
      for (const row of data ?? []) {
        const p = storagePath(row.legacy_image);
        if (p) items.push({ source: "notebook", id: row.entry_id ?? row.id, date: row.date, field: "legacy_image", path: p });
        for (const path of collectPaths(row.journal)) {
          items.push({ source: "notebook", id: row.entry_id ?? row.id, date: row.date, field: "journal", path });
        }
      }
    }
    if (!trade_id && wanted.has("daily_plans")) {
      let q = sb.from("daily_plans").select("id,date,result_chart_image,pairs,notes_journal,review_video").eq("user_id", uid);
      if (from) q = q.gte("date", from);
      if (to) q = q.lte("date", to);
      const { data, error } = await q.order("date", { ascending: false }).limit(500);
      if (error) return failure(error.message);
      for (const row of data ?? []) {
        const p = storagePath(row.result_chart_image);
        if (p) items.push({ source: "daily_plan", id: row.id, date: row.date, field: "result_chart_image", path: p });
        for (const path of collectPaths([row.pairs, row.notes_journal, row.review_video])) {
          items.push({ source: "daily_plan", id: row.id, date: row.date, field: "content", path });
        }
      }
    }
    const seen = /* @__PURE__ */ new Set();
    const unique = items.filter((i) => seen.has(i.path) ? false : (seen.add(i.path), true));
    const take = limit ?? 50;
    const page = unique.slice(0, take);
    let signed = /* @__PURE__ */ new Map();
    if (sign && page.length) {
      const { data, error } = await sb.storage.from(BUCKET).createSignedUrls(page.map((i) => i.path), expires_in ?? 3600);
      if (error) return failure(error.message);
      signed = new Map((data ?? []).filter((d) => d.signedUrl).map((d) => [String(d.path), d.signedUrl]));
    }
    return ok({
      total_found: unique.length,
      returned: page.length,
      signed: !!sign,
      expires_in: sign ? expires_in ?? 3600 : null,
      media: page.map((i) => ({ ...i, signed_url: signed.get(i.path) ?? null }))
    });
  }
});

// src/lib/mcp/index.ts
var projectRef = "gdrzwezxaofpucbwkrcr";
var mcp_default = defineMcp({
  name: "tg-master-journal-mcp",
  title: "TG Master Journal",
  version: "0.4.0",
  instructions: "Tools for TG Master Journal, a professional trading operating system. Dashboard & analytics: `get_dashboard_summary`, `get_performance_metrics` (win rate, profit factor, expectancy, optional breakdown by session/asset/setup/grade), `get_equity_curve`, `get_period_stats`, `get_trade_stats`. Trades: `list_trades` (filter by pair, session, setup, grade, result, direction, date range, min RR; sorted and paginated), `search_trades`, `get_trade`, `list_recent_trades`. Planning: `get_daily_plan`, `list_daily_plans`, `get_weekly_plan`. Routine & journal: `get_checklist`, `search_notebook`. Search & analysis: `search_journal` (ranked full-journal text search with snippets), `analyze_mistakes` (recurring violations and their cost), `analyze_setups` (strongest/weakest setups, assets, sessions), `analyze_psychology` (emotions, discipline, sentiment vs outcomes), `get_consistency_report`, `get_monthly_summary`, `get_weekly_report`. Writes (always confirm with the user first): `create_trade`, `update_trade`, `delete_trade` (needs confirm: true), `upsert_daily_plan`, `upsert_weekly_plan`, `create_notebook_entry`, `update_checklist`. Media: `list_media` and `get_media_url` return short-lived signed URLs for chart screenshots. All tools are scoped to the signed-in user and enforce row-level security; no tool can read or write another user's data or execute SQL. Prefer filtered, paginated calls over fetching everything.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    get_dashboard_summary_default,
    get_performance_metrics_default,
    get_equity_curve_default,
    get_period_stats_default,
    get_trade_stats_default,
    list_trades_default,
    search_trades_default,
    get_trade_default,
    list_recent_trades_default,
    get_daily_plan_default,
    list_daily_plans_default,
    get_weekly_plan_default,
    get_checklist_default,
    search_notebook_default,
    search_journal_default,
    analyze_mistakes_default,
    analyze_setups_default,
    analyze_psychology_default,
    get_consistency_report_default,
    get_monthly_summary_default,
    get_weekly_report_default,
    create_trade_default,
    update_trade_default,
    delete_trade_default,
    upsert_daily_plan_default,
    upsert_weekly_plan_default,
    create_notebook_entry_default,
    update_checklist_default,
    get_media_url_default,
    list_media_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
