// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/list-recent-trades.ts
import { createClient } from "npm:@supabase/supabase-js@^2.100.1";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.25.76";
function supabaseForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_recent_trades_default = defineTool({
  name: "list_recent_trades",
  title: "List recent trades",
  description: "List the signed-in user's most recent trades from TG Master Journal, ordered by date. Returns core fields (asset, direction, session, setup, grade, planned/actual RR, P/L, result).",
  inputSchema: {
    limit: z.number().int().min(1).max(100).default(20).describe("Max trades to return (1-100). Default 20.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "Not authenticated." }], isError: true };
    const sb = supabaseForUser(ctx);
    const { data, error } = await sb.from("trades").select(
      "id,date,asset,market,direction,session,setup,grade,planned_rr,actual_rr,profit_loss,result,status"
    ).eq("user_id", ctx.getUserId()).order("date", { ascending: false }).limit(limit ?? 20);
    if (error)
      return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { trades: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-trade-stats.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.100.1";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^3.25.76";
function supabaseForUser2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_trade_stats_default = defineTool2({
  name: "get_trade_stats",
  title: "Get trade performance stats",
  description: "Compute aggregate performance stats (trade count, win rate, total P/L, average R) across the signed-in user's trades, optionally filtered to the last N days.",
  inputSchema: {
    days: z2.number().int().min(1).max(3650).optional().describe("Only include trades from the last N days. Omit for all-time stats.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ days }, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "Not authenticated." }], isError: true };
    const sb = supabaseForUser2(ctx);
    let q = sb.from("trades").select("profit_loss,actual_rr,result,date").eq("user_id", ctx.getUserId());
    if (days) {
      const since = new Date(Date.now() - days * 864e5).toISOString().slice(0, 10);
      q = q.gte("date", since);
    }
    const { data, error } = await q;
    if (error)
      return { content: [{ type: "text", text: error.message }], isError: true };
    const rows = data ?? [];
    const count = rows.length;
    const wins = rows.filter((r) => r.result === "win").length;
    const losses = rows.filter((r) => r.result === "loss").length;
    const pnl = rows.reduce((s, r) => s + (Number(r.profit_loss) || 0), 0);
    const rValues = rows.map((r) => Number(r.actual_rr)).filter((v) => Number.isFinite(v));
    const avgR = rValues.length ? rValues.reduce((a, b) => a + b, 0) / rValues.length : 0;
    const stats = {
      window: days ? `last ${days} days` : "all time",
      trades: count,
      wins,
      losses,
      win_rate_pct: count ? +(wins / count * 100).toFixed(2) : 0,
      total_profit_loss: +pnl.toFixed(2),
      average_r: +avgR.toFixed(3)
    };
    return {
      content: [{ type: "text", text: JSON.stringify(stats, null, 2) }],
      structuredContent: stats
    };
  }
});

// src/lib/mcp/tools/get-daily-plan.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.100.1";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^3.25.76";
function supabaseForUser3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_daily_plan_default = defineTool3({
  name: "get_daily_plan",
  title: "Get daily trading plan",
  description: "Fetch the signed-in user's daily trading plan for a specific date (YYYY-MM-DD). Defaults to today when no date is supplied.",
  inputSchema: {
    date: z3.string().regex(/^\d{4}-\d{2}-\d{2}$/).optional().describe("Plan date in YYYY-MM-DD. Defaults to today.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ date }, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "Not authenticated." }], isError: true };
    const target = date ?? (/* @__PURE__ */ new Date()).toISOString().slice(0, 10);
    const sb = supabaseForUser3(ctx);
    const { data, error } = await sb.from("daily_plans").select("*").eq("user_id", ctx.getUserId()).eq("date", target).maybeSingle();
    if (error)
      return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data)
      return {
        content: [{ type: "text", text: `No daily plan found for ${target}.` }],
        structuredContent: { date: target, plan: null }
      };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { date: target, plan: data }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "gdrzwezxaofpucbwkrcr";
var mcp_default = defineMcp({
  name: "tg-master-journal-mcp",
  title: "TG Master Journal",
  version: "0.1.0",
  instructions: "Read-only tools for TG Master Journal, a professional trading operating system. Use `list_recent_trades` to browse recent trades, `get_trade_stats` for aggregate performance (win rate, total P/L, average R), and `get_daily_plan` to fetch a day's trading plan. All tools are scoped to the signed-in user.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_recent_trades_default, get_trade_stats_default, get_daily_plan_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
